# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi_id', models.IntegerField()),
                ('fi_cod_prov', models.CharField(max_length=3)),
                ('fi_cod_can', models.CharField(max_length=3)),
                ('fi_cod_par', models.CharField(max_length=3)),
                ('fi_cod_zon', models.CharField(max_length=3)),
                ('fi_cod_sec', models.CharField(max_length=3)),
                ('fi_cod_pol', models.CharField(max_length=3)),
                ('fi_cod_pre', models.CharField(max_length=3)),
                ('fi_cod_div', models.CharField(max_length=3)),
                ('fi_cod_ant_pre', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='cat_fichas',
        ),
    ]
