# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0002_auto_20160905_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='propietarios',
            fields=[
                ('pr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pr_dni', models.CharField(max_length=10)),
                ('pr_apellido', models.CharField(max_length=45)),
                ('pr_nombre', models.CharField(max_length=45)),
                ('pr_fec_nac', models.DateField()),
                ('pr_prop_ant', models.CharField(max_length=50)),
                ('pr_dir', models.CharField(max_length=50)),
                ('pr_tel', models.CharField(max_length=10)),
                ('pr_email', models.CharField(max_length=40)),
                ('pr_residencia_pro', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='fichas',
            name='id',
        ),
        migrations.AlterField(
            model_name='fichas',
            name='fi_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
