# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0003_auto_20160905_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichas',
            name='pr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
    ]
