# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0004_fichas_pr_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichas',
            old_name='pr_id',
            new_name='pr',
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
    ]
