# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0005_auto_20160905_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietarios',
            name='pr_rep_legal_dir',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='pr_rep_legal_dni',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='pr_rep_legal_nombre',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='pr_rep_legal_tel',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
    ]
