# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0007_auto_20160906_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_fec_nac',
            field=models.DateField(null=True),
        ),
    ]
