# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0008_auto_20160906_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas',
            name='fi_cod_ant_pre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_dir',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_dni',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_prop_ant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_rep_legal_dir',
            field=models.CharField(default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_rep_legal_dni',
            field=models.CharField(default=b'', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_rep_legal_nombre',
            field=models.CharField(default=b'', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_rep_legal_tel',
            field=models.CharField(default=b'', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_residencia_pro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='pr_tel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
