# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0013_auto_20160906_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietarios',
            name='pr_rep_legal_tel',
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
    ]
