# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0015_auto_20160906_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carac_Fisi_Predios',
            fields=[
                ('cfi_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfi_sect_homo', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_cal_suelo', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_superficie', models.FloatField(blank=True, null=True)),
                ('cfi_area_total', models.FloatField(blank=True, null=True)),
                ('cfi_perimetro', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_form_predio', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_topografia', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_tipo_riesgo', models.CharField(blank=True, max_length=45, null=True)),
                ('cfi_erosion', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carac_Princ_Edific',
            fields=[
                ('cr_id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_nro_bloque', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_nro_piso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_cod_uso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_uso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_area_piso', models.FloatField(blank=True, null=True)),
                ('cr_area_bloque', models.FloatField(blank=True, null=True)),
                ('cr_mat_estruc_viga', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_estruc_columna', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_estruc_pared', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_estruc_entrepiso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_acab_piso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_acab_puerta', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_acab_ventana', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_acab_enlucido', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_mat_acab_cielorraso', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_instal_electrica', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_instal_sanitaria', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_instal_banio', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('cr_anio_constr', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escrituras',
            fields=[
                ('es_id', models.AutoField(primary_key=True, serialize=False)),
                ('es_nro_notaria', models.CharField(blank=True, max_length=45, null=True)),
                ('es_canton', models.CharField(blank=True, max_length=45, null=True)),
                ('es_nro_reg_prop', models.CharField(blank=True, max_length=45, null=True)),
                ('es_fecha', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ident_Divisiones',
            fields=[
                ('id_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aprobacion', models.CharField(blank=True, max_length=45, null=True)),
                ('id_responsable_aprob', models.CharField(blank=True, max_length=45, null=True)),
                ('id_fecha_aprobacion', models.CharField(blank=True, max_length=45, null=True)),
                ('id_nombre_lotizacion', models.CharField(blank=True, max_length=45, null=True)),
                ('id_nro_lote', models.CharField(blank=True, max_length=45, null=True)),
                ('id_cod_jace', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infra_Serv_Vias',
            fields=[
                ('iv_id', models.AutoField(primary_key=True, serialize=False)),
                ('iv_tipo_vial', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_mat_calzada', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_agua_consumo_hum', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_energia_electrica', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_alumbrado_public', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_estado_via', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_pobla_cerca_predio', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_alcantarillado', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_telefonia', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_mat_poste_predio', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_nro_poste_predio', models.CharField(blank=True, max_length=45, null=True)),
                ('iv_transporte_public', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ir_Internas',
            fields=[
                ('iri_id', models.AutoField(primary_key=True, serialize=False)),
                ('iri_cod', models.CharField(blank=True, max_length=45, null=True)),
                ('iri_desc', models.CharField(blank=True, max_length=45, null=True)),
                ('iri_tipo_mat', models.CharField(blank=True, max_length=45, null=True)),
                ('iri_cant', models.FloatField(blank=True, null=True)),
                ('iri_unidad', models.FloatField(blank=True, null=True)),
                ('iri_estado', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ir_Otras',
            fields=[
                ('iro_id', models.AutoField(primary_key=True, serialize=False)),
                ('iro_cod', models.CharField(blank=True, max_length=45, null=True)),
                ('iro_desc', models.CharField(blank=True, max_length=45, null=True)),
                ('iro_superficie', models.CharField(blank=True, max_length=45, null=True)),
                ('iro_unid', models.CharField(blank=True, max_length=45, null=True)),
                ('iro_cant', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linderos',
            fields=[
                ('li_id', models.AutoField(primary_key=True, serialize=False)),
                ('li_punto_card', models.CharField(blank=True, max_length=45, null=True)),
                ('li_nom_propietario', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('ob_id', models.AutoField(primary_key=True, serialize=False)),
                ('ob_desc', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Cartog',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('rc_descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('rc_cod', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responsables',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False)),
                ('re_empadronado', models.CharField(blank=True, max_length=45, null=True)),
                ('re_fecha_emp', models.DateField(blank=True, null=True)),
                ('re_revisado', models.CharField(blank=True, max_length=45, null=True)),
                ('re_fecha_rev', models.DateField(blank=True, null=True)),
                ('re_digitado', models.CharField(blank=True, max_length=45, null=True)),
                ('re_fecha_dig', models.DateField(blank=True, null=True)),
                ('re_jefe_avaluo_catas', models.CharField(blank=True, max_length=45, null=True)),
                ('re_fecha_jefe_aval_catas', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serv_Instal_Predios',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_abast_agua', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_evac_agua_servida', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_energia_elect', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('sp_riego', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situ_Legal',
            fields=[
                ('sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('sl_dominio', models.CharField(blank=True, max_length=45, null=True)),
                ('sl_desc_tenencia', models.CharField(blank=True, max_length=45, null=True)),
                ('sl_trans_dominio', models.CharField(blank=True, max_length=45, null=True)),
                ('sl_tipo_tenencia', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('ub_id', models.AutoField(primary_key=True, serialize=False)),
                ('ub_cod_sector', models.CharField(blank=True, max_length=45, null=True)),
                ('ub_nombre_sector', models.CharField(blank=True, max_length=45, null=True)),
                ('ub_cod_via', models.CharField(blank=True, max_length=45, null=True)),
                ('ub_nombre_via', models.CharField(blank=True, max_length=45, null=True)),
                ('ub_nombre_predio', models.CharField(blank=True, max_length=45, null=True)),
                ('ub_coordenadas_x', models.FloatField(blank=True, null=True)),
                ('ub_coordenadas_y', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='situ_legal',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='serv_instal_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='responsables',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='ref_cartog',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='linderos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='ir_otras',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='ir_internas',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='infra_serv_vias',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='ident_divisiones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='escrituras',
            name='sl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Situ_Legal'),
        ),
        migrations.AddField(
            model_name='carac_princ_edific',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='carac_fisi_predios',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
    ]
