# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0016_auto_20160910_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maq_Equipos',
            fields=[
                ('mq_id', models.AutoField(primary_key=True, serialize=False)),
                ('mq_denomicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('mq_marca', models.CharField(blank=True, max_length=45, null=True)),
                ('mq_anio', models.CharField(blank=True, max_length=45, null=True)),
                ('mq_estado', models.CharField(blank=True, max_length=45, null=True)),
                ('mq_numero', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semovientes',
            fields=[
                ('se_id', models.AutoField(primary_key=True, serialize=False)),
                ('se_especie', models.CharField(blank=True, max_length=45, null=True)),
                ('se_raza', models.CharField(blank=True, max_length=45, null=True)),
                ('se_edad', models.IntegerField(blank=True, null=True)),
                ('se_sangre', models.CharField(blank=True, max_length=45, null=True)),
                ('se_numero', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uso_Ocup_Predios',
            fields=[
                ('up_id', models.AutoField(primary_key=True, serialize=False)),
                ('up_uso_general', models.CharField(blank=True, max_length=45, null=True)),
                ('up_detalle_uso', models.CharField(blank=True, max_length=45, null=True)),
                ('up_edad', models.CharField(blank=True, max_length=45, null=True)),
                ('up_conservacion', models.CharField(blank=True, max_length=45, null=True)),
                ('up_extencion', models.FloatField(blank=True, null=True)),
                ('up_porcentaje', models.FloatField(blank=True, null=True)),
                ('up_cod_economico', models.CharField(blank=True, max_length=45, null=True)),
                ('up_desc_economico', models.CharField(blank=True, max_length=45, null=True)),
                ('up_tipo_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('up_edificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('up_nro_bloq_terminado', models.CharField(blank=True, max_length=45, null=True)),
                ('up_nro_bloq_construccion', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carac_fisi_predios',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='carac_princ_edific',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AlterField(
            model_name='ident_divisiones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='infra_serv_vias',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_internas',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_otras',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='linderos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ref_cartog',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='serv_instal_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='situ_legal',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='uso_ocup_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='semovientes',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='maq_equipos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
    ]
