# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0017_auto_20160910_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc_Predios',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False)),
                ('dp_sect_homo', models.CharField(blank=True, max_length=45, null=True)),
                ('dp_cal_suelo', models.CharField(blank=True, max_length=45, null=True)),
                ('dp_superficie', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carac_fisi_predios',
            name='cfi_area_total',
        ),
        migrations.RemoveField(
            model_name='carac_fisi_predios',
            name='cfi_cal_suelo',
        ),
        migrations.RemoveField(
            model_name='carac_fisi_predios',
            name='cfi_perimetro',
        ),
        migrations.RemoveField(
            model_name='carac_fisi_predios',
            name='cfi_sect_homo',
        ),
        migrations.RemoveField(
            model_name='carac_fisi_predios',
            name='cfi_superficie',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_conservacion',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_detalle_uso',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_edad',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_extencion',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_porcentaje',
        ),
        migrations.RemoveField(
            model_name='uso_ocup_predios',
            name='up_uso_general',
        ),
        migrations.AlterField(
            model_name='carac_fisi_predios',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='carac_princ_edific',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AlterField(
            model_name='ident_divisiones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='infra_serv_vias',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_internas',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_otras',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='linderos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='maq_equipos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ref_cartog',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='semovientes',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='serv_instal_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='situ_legal',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='uso_ocup_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AddField(
            model_name='desc_predios',
            name='cfi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Carac_Fisi_Predios'),
        ),
    ]
