# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predio', '0023_auto_20160912_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infra_serv_vias',
            name='iv_mat_poste_predio',
        ),
        migrations.RemoveField(
            model_name='infra_serv_vias',
            name='iv_nro_poste_predio',
        ),
        migrations.AlterField(
            model_name='carac_fisi_predios',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='carac_princ_edific',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='fichas',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Propietarios'),
        ),
        migrations.AlterField(
            model_name='ident_divisiones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='infra_serv_vias',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_internas',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ir_otras',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='linderos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='maq_equipos',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ref_cartog',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='responsables',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='semovientes',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='serv_instal_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='situ_legal',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
        migrations.AlterField(
            model_name='uso_ocup_predios',
            name='fi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='predio.Fichas'),
        ),
    ]
